# config/routes.yaml
# Main controller routes
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Logout route
app_logout:
    path: /logout
    methods: [GET, POST]